
icache_fill1.S: icache_loadgen.py
	python icache_loadgen.py 32768 1 icache_fill1 >$@

icache_fill8.S: icache_loadgen.py
	python icache_loadgen.py 4096 8 icache_fill8 >$@

icache_fill64.S: icache_loadgen.py
	python icache_loadgen.py 512 64 icache_fill64 >$@

icache_fill256.S: icache_loadgen.py
	python icache_loadgen.py 128 256 icache_fill256 >$@

icache_fill512.S: icache_loadgen.py
	python icache_loadgen.py 64 512 icache_fill512 >$@
